#!/usr/bin/env bash
# this script prints Best School and 4 bad luck 8 good luck
n=1
while [ "$n" -le 10 ]
do
	if [ $n == 4 ]
	then
		echo "bad luck"
	elif [ $n == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
